### ISSUE TITLE
Effects not working in shipping build

### ISSUE THREAD

**Issue by DaveFace** [DaveFace/UnrealRetroShaders#2]
2 reports of effects not working in 'shipping' builds of the game - specifically, resolution did not seem to be scaled.

**Comment by DaveFace** [comment]
Haven't been able to reproduce this so far (using 4.27.2 and Windows 11). I have tried various builds of the game, e.g.:
![image](https://user-images.githubusercontent.com/10385948/173236741-0092cbf9-0b8c-4fb6-a99d-ed67eee44e9c.png)

But the results seem to match a PIE or Standalone Debug view:
![image](https://user-images.githubusercontent.com/10385948/173236842-6f6fb185-acec-43b6-8b93-b243def04a32.png)

**Comment by anxietyin480p** [comment]
Hey, as requested on Reddit, here's a screenshot of my build settings:

https://i.imgur.com/Vx79rcm.png

Also, here are some screenshots of my PIE view vs my packaged view:

PIE - https://i.imgur.com/aL541yn.png

Packaged - https://i.imgur.com/rNeed1F.png


P.S. I'm using UE 4.26.2 on Windows 10

**Comment by DaveFace** [comment]
Right, I see the problem: anti-aliasing isn't disabled. Maybe my method in the blueprint doesn't work (or only works in debug) and I didn't notice because AA is **also** disabled in the project settings.

In Project Settings > Rendering > Default Settings try disabling Auto Exposure, Motion Blur, and set the AA Method to None.
![image](https://user-images.githubusercontent.com/10385948/173240632-07bf002e-917c-4cdf-9e28-1391489b1f76.png)

**Comment by anxietyin480p** [comment]
That worked brill, you were spot on. Thank you so much for your time and help! I don't suppose you have a Patreon or something? I'd like to show my gratitude for the pack as well as the help. :)

**Comment by DaveFace** [comment]
Awesome, glad that worked. I don't have a Patreon or anything like that, can't even plug my game since we don't have a Twitter yet! Just happy people are making use of the pack really.
